name: fast
description: A sample command-line application.
version: 1.2.2
# homepage: https://www.example.com
executables: 
  fast: fast 

environment:
  sdk: '>=2.17.6 <3.0.0'


dependencies:
  path: ^1.8.2
  args: ^2.3.1
  interact: ^2.1.1
  grinder: ^0.9.2
  dart_style: ^2.2.4
 
 


 
 

 
 
 
 

 
  

  
  

  
 
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0




