name: fast_lite
description: This CLI allows the user to quickly create project structures based on clean architecture and provider.
version: 1.0.6
homepage: https://github.com/cristianpaulo4/fast
executables: 
  fast_lite: fast_lite 

environment:
  sdk: '>=3.2.1 <4.0.0'


dependencies:
  path: ^1.8.2
  args: ^2.3.1
  interact: ^2.1.1
  grinder: ^0.9.2
  dart_style: ^2.2.4
 
 
  
 
 
 
 
 
 
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0




